spring:
  profiles:
    active: kafka
  application:
    name: notification-service
  config:
    import: configserver:http://localhost:8888
  data:
    mongodb:
      database: Notification-service  # Ensure this is your intended database name
      host: localhost         # Ensure MongoDB is running on this host
      port: 27017             # Ensure MongoDB is listening on this port
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: user-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
server:
  port: 8085
  servlet:
    context-path: /api/notifications
eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${server.port}
    hostname: localhost
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    com.Ecommerce.Gateway_Service: DEBUG
    org.springframework.data.redis: DEBUG
    org.springframework.web.cors: DEBUG
    io.github.resilience4j: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
    com.Ecommerce: DEBUG  # Your package
    org.springframework.kafka: DEBUG
    org.apache.kafka: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

