# src/main/resources/application.yml
server:
  port: 8084
  servlet:
    context-path: /api/loyalty

#
#springdoc:
#  api-docs:
#    path: /api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#    operations-sorter: method
#    tags-sorter: alpha
#    doc-expansion: none
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
spring:
  profiles:
    active: kafka
  config:
    import: optional:configserver:http://localhost:8888
  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/loyalty-service
    username: postgres
#    password: yahyasd56
    password: zakaria
    driver-class-name: org.postgresql.Driver
  
  # JPA / Hibernate configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
  
  # Jackson configuration for date/time serialization
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
  application:
    name: loyalty-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: user-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

## Logging configuration
#logging:
#  level:
#    com.loyalty: DEBUG
#    org.springframework: INFO
#    org.hibernate: INFO
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

loyalty:
  tier:
    # Tier thresholds (points required to reach each tier)
    bronze-threshold: 0       # 0-499 points
    silver-threshold: 500     # 500-1999 points
    gold-threshold: 2000      # 2000-4999 points
    platinum-threshold: 5000  # 5000-9999 points
    diamond-threshold: 10000  # 10,000+ points

  # Point earning rates
  points:
    order-rate: 1.0           # Points per dollar spent
    review-points: 10         # Points for product review
    signup-bonus: 100         # Welcome bonus points
    first-order-bonus: 100    # First order bonus points
    referral-bonus: 200       # Referral bonus points

  # Coupon configuration
  coupons:
    default-validity-months: 3  # Default coupon validity
    max-stacking: 3            # Maximum coupons that can be stacked

  # Factory settings
  factory:
    create-default-data: true
    create-test-data: false
eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${server.port}
    hostname: localhost
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}

# Logging Configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    com.Ecommerce.Gateway_Service: DEBUG
    org.springframework.data.redis: DEBUG
    org.springframework.web.cors: DEBUG
    io.github.resilience4j: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
    com.Ecommerce: DEBUG  # Your package
    org.springframework.kafka: DEBUG
    org.apache.kafka: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
