server:
  port: 8099

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        # User Service API Routes
        - id: user-service-api
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

        # User Service Swagger UI
        - id: user-service-swagger-ui
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/swagger-ui/**
          filters:
            - RewritePath=/user-service/swagger-ui/(?<segment>.*), /swagger-ui/$\{segment}

        # User Service API Docs
        - id: user-service-api-docs
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/v3/api-docs/**
          filters:
            - RewritePath=/user-service/v3/api-docs/(?<segment>.*), /v3/api-docs/$\{segment}
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.netflix: DEBUG
    com.netflix.discovery: DEBUG
    com.netflix.eureka: DEBUG