spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Product-service
    username: your_database_username
    password: your_database_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
    platform: postgresql
  jpa:
    hibernate:
      ddl-auto: update  # Change to 'none' or 'validate' based on your use case
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 8080
