spring:
  data:
    mongodb:
      database: Cart-service  # Ensure this is your intended database name
      host: localhost         # Ensure MongoDB is running on this host
      port: 27017             # Ensure MongoDB is listening on this port
    redis:
      host: localhost
      port: 6379
      timeout: 2000
      # Add these if using authentication
      # password: your_password
    cache:
      type: redis
      redis:
        time-to-live: 600000  # Default cache TTL in milliseconds (10 minutes)
        cache-null-values: false
server:
  port: 8087
management:
  tracing:
    enabled: false
redis:
#  timeout: 2000
  maximumActiveConnectionCount: 128


kafka:
  bootstrap-servers: localhost:9092
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  consumer:
    group-id: cart-service-group
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: com.Ecommerce.Cart.Service